stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - cp $ENV .env
    - bash test.sh
  tags:
    - habit-app
  except:
    refs:
      - files
    changes:
        - "*.md"

deploy:
  except:
    refs:
      - files
    changes:
      - "*.md"
  stage: deploy
  needs: ["tests"]
  script:
    - cp $ENV .env
    - bash deploy.sh
  only:
    - main
  tags:
    - habit-app


