stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - cp $ENV .env
    - bash test.sh
  tags:
    - habit-app
  rules:
    - changes:
        - "*.md"
      when: never
    - when: always

deploy:
  stage: deploy
  needs: ["tests"]
  script:
    - cp $ENV .env
    - bash deploy.sh
  only:
    - main
  tags:
    - habit-app
  rules:
    - changes:
        - "*.md"
      when: never
    - when: always

