stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - cp $EN .env
    - bash test.sh
  tags:
    - habit-app

deploy:
  stage: deploy
  needs: ["tests"]
  script:
    - cp $ENV .env
    - bash deploy.sh
  only:
    - main
  tags:
    - habit-app
