stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - bash test.sh
    - python3 manage.py test
  tags:
    - habit-app

deploy:
  stage: deploy
  script:
    - cp $ENV .env
    - bash deploy.sh
  only:
    - main
  tags:
    - habit-app
