# Generated by Django 4.2.6 on 2023-10-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('nice_habit', models.BooleanField(default=True, verbose_name='Приятная привычка')),
                ('periodicity_in_days', models.PositiveIntegerField(default=1, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('completion_time_in_minutes', models.PositiveIntegerField(verbose_name='Время на выполнение в минутах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('habit_related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
