# Generated by Django 4.2.5 on 2023-09-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('nice_habit', models.BooleanField(default=True, verbose_name='Приятная привычка')),
                ('periodicity_in_days', models.IntegerField(default=1, verbose_name='Периодичность в днях')),
                ('habit_add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления привычки')),
                ('reward', models.CharField(max_length=255, verbose_name='Вознаграждение')),
                ('completion_time_in_minutes', models.PositiveIntegerField(verbose_name='Время на выполнение в минутах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('related_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
